### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by johnedelbi**
create a new branch `00-readme-v1`

update the readme file and add the following:

- [Contents](#)
  - [What can I cook?](#)
  - [tech](#)
  - [project aspect and roles](#)
  - [Agile planning](#)
    - [Must be](#)
    - [Should be](#)
    - [Could be](#)
  - [The RoadMap](#)
  - [design source](#)
  - [naming agreed roles](#)

### CODE REVIEW

**Comment by renjani2022** [comment]
looks good

**Review by renjani2022 — DISMISSED** [review]

**Review by bibhasingh — APPROVED** [review]
It looks good.

**Review by BrianMunene96 — APPROVED** [review]
- Nice Additions. Thank you for the logo.

**Review by V-Valkiriya — COMMENTED** [review]
Good job! Thank you! logo is cool. The tech style cool for the name of our team.👏 
But maybe for the name of the project to choose something more "cozy" and less"tech"? 🤔 :

**Review by V-Valkiriya — COMMENTED** [review]
.

**Pull request merged**
